server:
  port: 9010


spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
         destination: send-communication
         group: ${spring.application.name}
        emailsms-out-0:
         destination: communication-sent
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
    connection-timeout: 10s